services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: myDB
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "6000:3306"
